{% set name = "jekyll-sitemap" %}
{% set version = "1.4.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 0de08c5debc185ea5a8f980e1025c7cd3f8e0c35c8b6ef592f15c46235cf4218

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.7,<5.0

test:
  commands:
    - ruby -r jekyll -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Automatically generate a sitemap.xml for your Jekyll site.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/benbalter/{{ name }}

extra:
  recipe-maintainers:
    - sodre
