{% set name = "jekyll-sitemap" %}
{% set version = "1.3.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: b528e0bbd6eb3d4906b9df5fc3ad33d4710b615990f5309e22629d61d7c67c34

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.3,<4

test:
  commands:
    - ruby -r jekyll -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Automatically generate a sitemap.xml for your Jekyll site.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/benbalter/{{ name }}

extra:
  recipe-maintainers:
    - sodre
