travis:
  secure:
    BINSTAR_TOKEN: nRbGdYO4R33WYbhI/2aJNl3xszwlQIiW0RWrttc3mTij1fmaS8IWf0Jki7utBPMNt345myRdYqDlQb9awu20cSZvtYAlUp9TGQ+o3+xOHJ0BdtxXlMpyKpo2a7M2kWObGKygst3CF1yZGR+wIsoHEubzvCl1d5aiw9d4lLrwTVmFZD6e+8l9DyEakALCNtn0+OvZlO2eX8J/AMqVLfzk4E+67quoJHfieeetlIOh96GZ+DqAnFHrZTfRtD/KVonEt7eW67t22gLVynBrKlkBY4rkvaryXMveRFJkFxq9JyDLYODWll26PTe0FkISiJSVuNhiyWSrk11ZoyzU/4picjgbkaB3PYcmOiVtbV4wZlXM1CJ/C1tWjk4NqNJ9bVvU6NUw0Ku49veVWjm5K/Vmb5oh8L5FM/7sIguPOXkgT0BodjIqBv/Q6SqR00pmPP3jR/lBbhrCiuzonxRMDy7XG6STwgLBWucCWqApzwTvBQ+g51fF/rc/S6CToAef5l/nr/sM7BBfI6399BNwrlq8ZmyViOqvPdEyFykzoPzDf/zqOCbUBJ2rRn6JHNfN3FyMe9uUnOKRWKLyrawPE4XskHjdx9JTTOBGkH+s8X6kvM7oT0cAl2RpJ8Hxl/SfhBCLSTtQU88mZL1ED7j0cxhUcxxc4k0fkMmeMhd0D5ATM2A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
